name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.2-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - "5432:5432"
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432

    steps:
      # UNCOMMENT TO ADD CYPRESS TESTS, AFTER INITIALIZING PRISMA
      # - name: Checkout
      #   uses: actions/checkout@v2
      # # Install NPM dependencies, cache them correctly
      # # and run all Cypress tests
      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     build: npm run build:cypress
      #     start: npm run start:cypress
      #     record: true
      #   env:
      #     # pass the Dashboard record key as an environment variable
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #     # pass GitHub token to allow accurately detecting a build vs a re-run build
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
